### ISSUE TITLE
[Test Failed] Test 2 失败了

### ISSUE THREAD

**Issue by Toby-Shi-cloud** [Toby-Shi-cloud/Mars-with-BUAA-CO-extension#14]
Test 2 失败了，但是似乎没有改动过这个测试才对。
related to #12 #13 [actions#20](https://github.com/Toby-Shi-cloud/Mars-with-BUAA-CO-extension/actions/runs/11917740103)

**Comment by MessiXiang** [comment]
我琢磨一下，我没动过这个测试……

**Comment by MessiXiang** [comment]
我核实过了，由于p7提供了标准的mars，我对拍了一下，发现stdout2是错的，实际上目前咱这个mars出来的结果和课程组的一致，至于为什么会变，我暂时不知道。

**Comment by MessiXiang** [comment]
我试验了一下，code2.asm在编译的时候，由于`data_label3`分配的是4字节，也就是32bit，那么`lw $3, data_label3($3)`会在汇编的时候变成`lui+ori+lw`的伪指令，这一点我利用P7课下提供的官方mars验证了，而你目前merge的mars结果与之相同。

**Comment by MessiXiang** [comment]
因此我建议修改stdout2为课程组mars的输出，也就是伪指令。而本repo早期版本在翻译的时候并不会翻译出伪指令，这一点非常奇怪，我没有修改过相关代码，但是好消息就是目前本repo和课程组mars完全一致（只是不知道原因）。我在这里附上了课程组提供的mars以供您参考，如果没有问题的话我明天再提一个pr，之后我自己打tag等自动化测试了，就不麻烦您了。
[Mars_p7.zip](https://github.com/user-attachments/files/17818953/Mars_p7.zip)
