### ISSUE TITLE
栈限制地址问题

### ISSUE THREAD

**Issue by coder014** [Toby-Shi-cloud/Mars-with-BUAA-CO-extension#3]
提交：https://github.com/Toby-Shi-cloud/Mars-with-BUAA-CO-extension/commit/27ab2c68fa049e8ca264e269cbdc917e4fbd1bd8#diff-55743d03bcd6d9206e09758134cdfd9e2fe0046e25c591bd98dd907b82ed2e50R174
```
0x00002ffc, // stack base address
......
0x00005000, // stack limit address
```
一般栈在内存空间中是向低地址增长的，即栈基址>=栈顶地址>=栈限制地址，所以`stack limit address`是否应该与`heap base address`对齐？

**Comment by Toby-Shi-cloud** [comment]
本意确实只是想把0x3000以上的+0x3000，结果不小心吧这个原来的0x2000的`stack limit address`更改到了。感谢指正。不过或许是因为我们的实验没有用到堆栈，所以没有出现什么问题。

**Comment by coder014** [comment]
Fixed in ebd96e62170dba1c96f52e67a6ece1d09128d1c2
