### ISSUE TITLE
$gp,$sp 初始化问题

### ISSUE THREAD

**Issue by coder014** [Toby-Shi-cloud/Mars-with-BUAA-CO-extension#4]
根据课程组要求，CPU初始化/复位时所有寄存器值应为`0`，原版MARS则会复位`$gp`、`$sp`至当前内存布局配置中对应的值。
希望能引入新的命令行参数开关以启用该特性。

**Comment by coder014** [comment]
相关问题 #3 
MARS可能会对$gp、$sp的值做特殊检查，如寄存器取值不满足内存布局限制范围可能引发程序内异常。
可能需要屏蔽这种检查机制，或进一步魔改内存布局配置。

**Comment by Toby-Shi-cloud** [comment]
我发现了……我正在进行自动化测试……所以只能干脆少用了几个寄存器进行测试……

目前我发现我的P4的jal跳转或许有些问题，等我改完再考虑考虑（悲）
